/**
 * ─────────────────────────────────────────────────────────────────────────
 *  Payments.jsx — Payment Management module
 *
 *  Two tabs:
 *    • Payments — read-only history of every payment collected against a
 *      sale (auto-generated by the backend on sale completion / loan
 *      repayment). Search, filter (method / bank / date range), sort,
 *      and paginate. ADMIN can edit the note/reference or delete a record;
 *      WORKER has view-only access.
 *    • Banks — CRUD (create, edit, deactivate, delete) for the banks the
 *      store accepts payments through, with search. ADMIN only for writes;
 *      WORKER can view (read-only) so the list makes sense to them, but the
 *      Sales-form bank picker itself pulls from a separate lightweight
 *      endpoint (getActiveBanks), not this page.
 *
 *  Every record shown here is already de-identified by the backend —
 *  payment/sale database ids are never sent to the client. Payments only
 *  carry human-facing codes (PAY-000123 / SALE-000045).
 * ─────────────────────────────────────────────────────────────────────────
 */
import { useState, useEffect } from 'react';
import {
  Search, Plus, Trash2, Edit2, Wallet, Landmark, Receipt,
  ChevronLeft, ChevronRight, X, RefreshCw, Calendar,
  CheckCircle, ArrowUpDown, Ban, CheckCircle2,
} from 'lucide-react';
import {
  getPaymentsPage, updatePaymentNotes, deletePayment,
  getBanksPage, createBank, updateBank, deleteBank,
} from '../services/api';

/* ─────────────────────────────────────────────────────────────────────────────
   Design-system CSS — same token set as Sales / Finance / Products
   ───────────────────────────────────────────────────────────────────────── */
const PAY_CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400&family=DM+Sans:wght@300;400;500&display=swap');

  .abk-pay {
    --cream:         #F0F7E2;
    --cream-deep:    #E4F0CF;
    --ink:           #0F1F04;
    --ink-mid:       #3A5220;
    --ink-light:     #6A8A4A;
    --ink-faint:     #A8C080;
    --border:        #D0E4B0;
    --border-light:  #E2EFC8;
    --card:          #FFFFFF;
    --card-hover:    #F3FAE6;
    --green:         #1D9E75;
    --green-bg:      #E1F5EE;
    --blue:          #185FA5;
    --blue-bg:       #E6F1FB;
    --purple:        #534AB7;
    --purple-bg:     #EEEDFE;
    --amber:         #854F0B;
    --amber-bg:      #FAEEDA;
    --red-bg:        #FCEBEB;
    --red-border:    #F7C1C1;
    --red-text:      #791F1F;
    --yellow-bg:     #FAEEDA;
    --yellow-border: #FAC775;
    --texture-col:   #C8DCA8;
  }

  .abk-pay.abk-dark {
    --cream:         #0D1117;
    --cream-deep:    #161B22;
    --ink:           #E6EDF3;
    --ink-mid:       #B8C9DB;
    --ink-light:     #8BA4BE;
    --ink-faint:     #5A7A96;
    --border:        #21303F;
    --border-light:  #1A2535;
    --card:          #13192A;
    --card-hover:    #1C2540;
    --green:         #3DD68C;
    --green-bg:      #0D2B1F;
    --blue:          #58A6FF;
    --blue-bg:       #0D1F35;
    --purple:        #A78BFA;
    --purple-bg:     #1A1535;
    --amber:         #F0A742;
    --amber-bg:      #2A1C06;
    --red-bg:        #1F0D0D;
    --red-border:    #3D1515;
    --red-text:      #FF8080;
    --yellow-bg:     #1F1608;
    --yellow-border: #3D2A0A;
    --texture-col:   #1A2535;
  }

  .abk-pay, .abk-pay * { font-family:'DM Sans',sans-serif; box-sizing:border-box; }
  .abk-pay .abk-serif   { font-family:'Playfair Display',Georgia,serif !important; }

  .abk-pay.abk-texture::before {
    content:''; position:fixed; inset:0; pointer-events:none; z-index:0;
    background-image:
      linear-gradient(var(--texture-col) 1px, transparent 1px),
      linear-gradient(90deg, var(--texture-col) 1px, transparent 1px);
    background-size:48px 48px; opacity:.25;
  }
  .abk-pay.abk-dark.abk-texture::before { opacity:.18; }

  @keyframes abkPFadeUp  { from{opacity:0;transform:translateY(16px)} to{opacity:1;transform:translateY(0)} }
  @keyframes abkPFadeIn  { from{opacity:0} to{opacity:1} }
  @keyframes abkPScaleIn { from{opacity:0;transform:scale(.94)} to{opacity:1;transform:scale(1)} }
  @keyframes abkPToast   { 0%{opacity:0;transform:translateY(-12px)} 10%{opacity:1;transform:translateY(0)} 85%{opacity:1} 100%{opacity:0} }

  .abk-pay .abk-anim-fade-up  { opacity:0; animation:abkPFadeUp  .45s ease both; }
  .abk-pay .abk-anim-fade-in  { opacity:0; animation:abkPFadeIn  .45s ease both; }
  .abk-pay .abk-anim-scale-in { opacity:0; animation:abkPScaleIn .45s ease both; }
  .abk-pay .abk-toast         { animation:abkPToast 3.2s ease forwards; }

  .abk-pay .abk-row-hover { transition:background .15s; }
  .abk-pay .abk-row-hover:hover { background:var(--card-hover) !important; }

  .abk-pay .abk-input {
    width:100%; border:1px solid var(--border); border-radius:10px;
    padding:9px 12px; font-size:13px; color:var(--ink);
    background:var(--card); outline:none;
    transition:border-color .15s, box-shadow .15s;
    font-family:'DM Sans',sans-serif;
  }
  .abk-pay .abk-input:focus {
    border-color:var(--blue);
    box-shadow:0 0 0 3px rgba(24,95,165,.12);
  }
  .abk-pay .abk-input::placeholder { color:var(--ink-faint); }
  .abk-pay.abk-dark .abk-input    { background:var(--cream-deep); }

  .abk-pay select.abk-input { cursor:pointer; }

  .abk-pay .abk-label {
    display:block; font-size:10.5px; font-weight:600;
    text-transform:uppercase; letter-spacing:.09em;
    color:var(--ink-light); margin-bottom:6px;
  }

  .abk-pay ::-webkit-scrollbar       { width:5px; }
  .abk-pay ::-webkit-scrollbar-track { background:transparent; }
  .abk-pay ::-webkit-scrollbar-thumb { background:var(--border); border-radius:4px; }

  .abk-pay .abk-tab-btn {
    padding:8px 16px; border-radius:10px; font-size:12.5px; font-weight:600;
    cursor:pointer; border:1px solid var(--border); background:var(--card);
    color:var(--ink-light); transition:all .15s; font-family:'DM Sans',sans-serif;
    display:inline-flex; align-items:center; gap:6px;
  }
  .abk-pay .abk-tab-btn.active {
    background:var(--blue-bg); color:var(--blue); border-color:var(--blue);
  }

  @media (max-width:1023px) {
    .abk-pay-kpi-3  { grid-template-columns: repeat(2,minmax(0,1fr)) !important; }
    .abk-pay-filter { flex-wrap: wrap !important; }
    .abk-pay-filter > * { min-width: 140px !important; }
  }

  @media (max-width:767px) {
    .abk-pay-pad    { padding: 1rem 0.75rem 3rem !important; }
    .abk-pay-kpi-3  { grid-template-columns: 1fr !important; }
    .abk-pay-filter { flex-direction: column !important; }
    .abk-pay-filter > * { width: 100% !important; }
    .abk-pay-header { flex-direction: column !important; align-items: flex-start !important; gap: 10px !important; }
    .abk-pay-header > * { width: 100% !important; }
    .abk-pay-modal-grid { grid-template-columns: 1fr !important; }
    .abk-pay-table-wrap { overflow-x: auto !important; -webkit-overflow-scrolling: touch !important; }
    .abk-pay-table-wrap table { min-width: 780px !important; table-layout: auto !important; }
  }

  @media (max-width:480px) {
    .abk-pay-pad { padding: 0.75rem 0.5rem 2rem !important; }
    .abk-pay-kpi-3 { grid-template-columns: 1fr !important; }
  }
  @media (max-width:767px) {
    input, select, textarea { font-size: 16px !important; }
  }
`;

/* ── helpers ──────────────────────────────────────────────────────────────── */
function fmt(n) {
  return (n ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
function fmtDate(d) {
  if (!d) return '—';
  return new Date(d + 'T00:00:00').toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}
function fmtTime(t) {
  if (!t) return '';
  const [h, m] = t.split(':');
  const hr = parseInt(h);
  return `${hr % 12 || 12}:${m} ${hr >= 12 ? 'PM' : 'AM'}`;
}

/* ── shared UI atoms ──────────────────────────────────────────────────────── */
function Modal({ onClose, children, maxWidth = 480 }) {
  return (
    <div style={{
      position: 'fixed', inset: 0, background: 'rgba(0,0,0,.45)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 50, padding: 16, backdropFilter: 'blur(4px)',
    }}>
      <div className="abk-anim-scale-in" style={{
        background: 'var(--card)', borderRadius: 18, width: '100%', maxWidth,
        maxHeight: '90vh', overflowY: 'auto',
        boxShadow: '0 20px 60px rgba(0,0,0,.2), 0 2px 8px rgba(0,0,0,.1)',
        border: '1px solid var(--border)',
      }}>{children}</div>
    </div>
  );
}

function ModalHeader({ title, subtitle, onClose, accent }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      padding: '1.1rem 1.4rem', borderBottom: '1px solid var(--border-light)',
      position: 'relative', overflow: 'hidden',
    }}>
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: accent }} />
      <div style={{ marginTop: 4 }}>
        <div className="abk-serif" style={{ fontSize: 16, fontWeight: 500, color: 'var(--ink)' }}>{title}</div>
        {subtitle && <div style={{ fontSize: 11, color: 'var(--ink-faint)', marginTop: 2, fontWeight: 300 }}>{subtitle}</div>}
      </div>
      <button onClick={onClose} style={{
        width: 30, height: 30, borderRadius: 8, border: '1px solid var(--border)',
        background: 'var(--cream-deep)', display: 'flex', alignItems: 'center',
        justifyContent: 'center', cursor: 'pointer', color: 'var(--ink-light)',
      }}><X size={14} /></button>
    </div>
  );
}

function ModalFooter({ children }) {
  return (
    <div style={{ display: 'flex', gap: 10, padding: '1rem 1.4rem', borderTop: '1px solid var(--border-light)' }}>
      {children}
    </div>
  );
}

function BtnPrimary({ onClick, disabled, children, color = 'var(--blue)' }) {
  return (
    <button onClick={onClick} disabled={disabled} style={{
      flex: 1, padding: '10px 0', background: color, color: '#fff',
      border: 'none', borderRadius: 11, fontSize: 13, fontWeight: 500,
      cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? .5 : 1,
      display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
      transition: 'filter .15s', fontFamily: 'DM Sans,sans-serif',
    }}
      onMouseEnter={e => { if (!disabled) e.currentTarget.style.filter = 'brightness(1.08)'; }}
      onMouseLeave={e => { e.currentTarget.style.filter = 'none'; }}
    >{children}</button>
  );
}

function BtnSecondary({ onClick, children }) {
  return (
    <button onClick={onClick} style={{
      flex: 1, padding: '10px 0', background: 'var(--cream-deep)', color: 'var(--ink-mid)',
      border: '1px solid var(--border)', borderRadius: 11, fontSize: 13, fontWeight: 500,
      cursor: 'pointer', fontFamily: 'DM Sans,sans-serif',
    }}
      onMouseEnter={e => e.currentTarget.style.background = 'var(--border)'}
      onMouseLeave={e => e.currentTarget.style.background = 'var(--cream-deep)'}
    >{children}</button>
  );
}

function KpiCard({ label, value, sub, Icon, stripeColor, iconBg, iconColor, delay }) {
  return (
    <div className="abk-anim-fade-up" style={{
      background: 'var(--card)', border: '1px solid var(--border)',
      borderRadius: 14, padding: '1.1rem 1.1rem .9rem',
      position: 'relative', overflow: 'hidden', animationDelay: delay,
      boxShadow: '0 1px 4px rgba(0,0,0,.06)',
    }}>
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: stripeColor }} />
      <div style={{
        width: 32, height: 32, borderRadius: 8, background: iconBg,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        marginBottom: 9, marginTop: 4,
      }}>
        <Icon size={15} color={iconColor} />
      </div>
      <div className="abk-serif" style={{
        fontSize: 22, fontWeight: 700, color: iconColor, letterSpacing: -0.3,
        marginBottom: 4, whiteSpace: 'nowrap', overflow: 'hidden',
        textOverflow: 'ellipsis', lineHeight: 1.15,
      }}>{value}</div>
      <div style={{ fontSize: 11, color: 'var(--ink-light)', fontWeight: 400 }}>{label}</div>
      <div style={{ fontSize: 10.5, color: 'var(--ink-faint)', fontWeight: 300, marginTop: 1 }}>{sub}</div>
    </div>
  );
}

function MethodBadge({ method }) {
  const isBank = method === 'BANK';
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: 4,
      fontSize: 11, fontWeight: 600, padding: '2px 9px', borderRadius: 20,
      background: isBank ? 'var(--blue-bg)' : 'var(--green-bg)',
      color: isBank ? 'var(--blue)' : 'var(--green)',
      border: `1px solid ${isBank ? 'rgba(24,95,165,.25)' : 'rgba(29,158,117,.25)'}`,
    }}>
      {isBank ? <Landmark size={10} /> : <Wallet size={10} />} {isBank ? 'Bank' : 'Cash'}
    </span>
  );
}

/* ════════════════════════════════════════════════════════════════════════════
   Payments component
   ════════════════════════════════════════════════════════════════════════════ */
export default function Payments({ dark, user }) {
  const isAdmin = user?.role?.toUpperCase() === 'ADMIN';

  /* Inject CSS once */
  useEffect(() => {
    const id = 'abk-pay-css';
    let tag = document.getElementById(id);
    if (!tag) { tag = document.createElement('style'); tag.id = id; document.head.appendChild(tag); }
    tag.innerHTML = PAY_CSS;
    return () => { const el = document.getElementById(id); if (el) el.remove(); };
  }, []);

  const [tab, setTab] = useState('payments'); // 'payments' | 'banks'
  const [successMsg, setSuccessMsg] = useState('');
  function showSuccess(msg) { setSuccessMsg(msg); setTimeout(() => setSuccessMsg(''), 3200); }

  return (
    <div className={`abk-pay abk-texture${dark ? ' abk-dark' : ''}`}
      style={{ background: 'var(--cream)', minHeight: '100vh', position: 'relative', transition: 'background .3s' }}>

      {successMsg && (
        <div className="abk-toast" style={{
          position: 'fixed', top: 20, right: 20, zIndex: 100,
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: 'var(--blue)', color: '#fff', padding: '10px 18px', borderRadius: 12,
          fontSize: 13, fontWeight: 500, boxShadow: '0 4px 20px rgba(24,95,165,.35)',
        }}>
          <CheckCircle size={15} /> {successMsg}
        </div>
      )}

      <div className="abk-pay-pad" style={{ position: 'relative', zIndex: 1, padding: '1.5rem 1.5rem 3rem' }}>

        {/* ── Page Header ──────────────────────────────────────────────── */}
        <div className="abk-anim-fade-up abk-pay-header" style={{ padding: '0.5rem 0 1.4rem', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 }}>
          <div>
            <div style={{ fontSize: 10.5, fontWeight: 500, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--ink-light)', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ display: 'inline-block', width: 18, height: 1.5, background: 'var(--blue)', borderRadius: 1 }} />
              Payments
            </div>
            <div className="abk-serif" style={{ fontSize: 28, fontWeight: 500, color: 'var(--ink)', letterSpacing: -0.5, lineHeight: 1.1 }}>
              Payment Management
            </div>
            <div style={{ fontSize: 12, color: 'var(--ink-faint)', marginTop: 4, fontWeight: 300 }}>
              Every payment collected against a sale, plus the banks you accept payments through.
            </div>
          </div>

          <div style={{ display: 'flex', gap: 8 }}>
            <button className={`abk-tab-btn${tab === 'payments' ? ' active' : ''}`} onClick={() => setTab('payments')}>
              <Receipt size={13} /> Payments
            </button>
            <button className={`abk-tab-btn${tab === 'banks' ? ' active' : ''}`} onClick={() => setTab('banks')}>
              <Landmark size={13} /> Banks
            </button>
          </div>
        </div>

        {tab === 'payments'
          ? <PaymentsTab dark={dark} isAdmin={isAdmin} showSuccess={showSuccess} />
          : <BanksTab isAdmin={isAdmin} showSuccess={showSuccess} />}
      </div>
    </div>
  );
}

/* ════════════════════════════════════════════════════════════════════════════
   Payments tab — search / filter / sort / pagination
   ════════════════════════════════════════════════════════════════════════════ */
function PaymentsTab({ dark, isAdmin, showSuccess }) {
  const [rows,           setRows]           = useState([]);
  const [totalElements,  setTotalElements]  = useState(0);
  const [totalPages,     setTotalPages]     = useState(1);
  const [loading,        setLoading]        = useState(true);
  const [search,         setSearch]         = useState('');
  const [method,         setMethod]         = useState('');
  const [dateFrom,       setDateFrom]       = useState('');
  const [dateTo,         setDateTo]         = useState('');
  const [sortBy,         setSortBy]         = useState('date');
  const [sortDir,        setSortDir]        = useState('desc');
  const [page,           setPage]           = useState(1);
  const [rowsPerPage,    setRowsPerPage]    = useState(10);
  const [editTarget,     setEditTarget]     = useState(null);
  const [deleteConfirm,  setDeleteConfirm]  = useState(null);
  const [editForm,       setEditForm]       = useState({ transactionRef: '', notes: '' });
  const [saving,         setSaving]         = useState(false);

  async function load() {
    try {
      setLoading(true);
      const res = await getPaymentsPage({
        page: page - 1, size: rowsPerPage, search, method,
        from: dateFrom, to: dateTo, sortBy, sortDir,
      });
      setRows(res.content ?? []);
      setTotalElements(res.totalElements ?? 0);
      setTotalPages(Math.max(1, res.totalPages ?? 1));
    } catch {
      setRows([]); setTotalElements(0); setTotalPages(1);
    } finally { setLoading(false); }
  }

  useEffect(() => {
    const t = setTimeout(load, search ? 350 : 0);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, rowsPerPage, search, method, dateFrom, dateTo, sortBy, sortDir]);

  function toggleSort(field) {
    if (sortBy === field) setSortDir(d => d === 'asc' ? 'desc' : 'asc');
    else { setSortBy(field); setSortDir('desc'); }
    setPage(1);
  }

  function openEdit(p) {
    setEditForm({ transactionRef: p.transactionRef || '', notes: p.notes || '' });
    setEditTarget(p);
  }

  async function handleSaveEdit() {
    setSaving(true);
    try {
      await updatePaymentNotes(editTarget.paymentCode, editForm);
      setEditTarget(null);
      showSuccess('Payment updated');
      await load();
    } catch (e) { alert(e.message || 'Failed to update payment.'); }
    finally { setSaving(false); }
  }

  async function handleDelete(code) {
    try {
      await deletePayment(code);
      setDeleteConfirm(null);
      showSuccess('Payment deleted');
      await load();
    } catch (e) { alert(e.message || 'Failed to delete payment.'); }
  }

  const cashCount = rows.filter(r => r.paymentMethod === 'CASH').length;
  const bankCount = rows.filter(r => r.paymentMethod === 'BANK').length;

  const hasFilters = search || method || dateFrom || dateTo;

  return (
    <>
      {/* ── KPI Cards (from current page — a quick pulse, not a full aggregate) ── */}
      <div className="abk-pay-kpi-3" style={{ display: 'grid', gridTemplateColumns: 'repeat(3,minmax(0,1fr))', gap: 10, marginBottom: '1.1rem' }}>
        <KpiCard label="Payments (this page)" value={totalElements}
          sub={`${cashCount} cash · ${bankCount} bank on this page`}
          Icon={Receipt} stripeColor="var(--blue)" iconBg="var(--blue-bg)" iconColor="var(--blue)" delay=".06s" />
        <KpiCard label="Cash on this page" value={`$${fmt(rows.filter(r => r.paymentMethod === 'CASH').reduce((a, r) => a + (r.amountPaid || 0), 0))}`}
          sub="Collected in cash" Icon={Wallet} stripeColor="var(--green)" iconBg="var(--green-bg)" iconColor="var(--green)" delay=".13s" />
        <KpiCard label="Bank on this page" value={`$${fmt(rows.filter(r => r.paymentMethod === 'BANK').reduce((a, r) => a + (r.amountPaid || 0), 0))}`}
          sub="Collected via bank" Icon={Landmark} stripeColor="var(--purple)" iconBg="var(--purple-bg)" iconColor="var(--purple)" delay=".20s" />
      </div>

      {/* ── Search & Filters ─────────────────────────────────────────── */}
      <div className="abk-anim-fade-in abk-pay-filter" style={{ display: 'flex', gap: 8, marginBottom: '1rem', animationDelay: '.28s', flexWrap: 'wrap' }}>
        <div style={{ flex: 2, minWidth: 200, position: 'relative' }}>
          <Search size={14} style={{ position: 'absolute', left: 11, top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-faint)', pointerEvents: 'none' }} />
          <input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}
            placeholder="Search customer, cashier, bank, code, ref…" className="abk-input" style={{ paddingLeft: 34 }} />
        </div>
        <select value={method} onChange={e => { setMethod(e.target.value); setPage(1); }} className="abk-input" style={{ minWidth: 120 }}>
          <option value="">All methods</option>
          <option value="CASH">Cash</option>
          <option value="BANK">Bank</option>
        </select>
        <div style={{ position: 'relative' }}>
          <Calendar size={13} style={{ position: 'absolute', left: 11, top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-faint)', pointerEvents: 'none' }} />
          <input type="date" value={dateFrom} onChange={e => { setDateFrom(e.target.value); setPage(1); }}
            className="abk-input" style={{ paddingLeft: 32, minWidth: 150, cursor: 'pointer', colorScheme: dark ? 'dark' : 'light' }} title="From date" />
        </div>
        <div style={{ position: 'relative' }}>
          <Calendar size={13} style={{ position: 'absolute', left: 11, top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-faint)', pointerEvents: 'none' }} />
          <input type="date" value={dateTo} onChange={e => { setDateTo(e.target.value); setPage(1); }}
            className="abk-input" style={{ paddingLeft: 32, minWidth: 150, cursor: 'pointer', colorScheme: dark ? 'dark' : 'light' }} title="To date" />
        </div>
        {hasFilters && (
          <button onClick={() => { setSearch(''); setMethod(''); setDateFrom(''); setDateTo(''); setPage(1); }} style={{
            display: 'inline-flex', alignItems: 'center', gap: 5, padding: '0 13px',
            background: 'var(--red-bg)', border: '1px solid var(--red-border)',
            borderRadius: 10, color: 'var(--red-text)', fontSize: 12, cursor: 'pointer', fontFamily: 'DM Sans,sans-serif',
          }}><X size={12} /> Clear</button>
        )}
      </div>

      {/* ── Table ─────────────────────────────────────────────────────── */}
      <div className="abk-anim-scale-in" style={{
        background: 'var(--card)', border: '1px solid var(--border)',
        borderRadius: 16, width: '100%', overflow: 'hidden',
        boxShadow: '0 2px 12px rgba(0,0,0,.06)', animationDelay: '.32s',
      }}>
        <div style={{
          padding: '10px 16px', borderBottom: '1px solid var(--border-light)',
          background: 'var(--cream-deep)', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <div className="abk-serif" style={{ fontSize: 14, fontWeight: 500, color: 'var(--ink)' }}>Payment History</div>
          <span style={{ fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>{totalElements} records</span>
        </div>

        <div className="abk-pay-table-wrap" style={{ overflowX: 'auto', width: '100%' }}>
          <table style={{ width: '100%', minWidth: 'max-content', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: 'var(--cream-deep)', borderBottom: '1px solid var(--border)' }}>
                {[
                  { key: 'date',     label: 'Date & Time' },
                  { key: null,       label: 'Payment Code' },
                  { key: 'customer', label: 'Customer' },
                  { key: null,       label: 'Sale' },
                  { key: 'method',   label: 'Method' },
                  { key: 'bank',     label: 'Bank' },
                  { key: 'amount',   label: 'Amount' },
                  { key: 'cashier',  label: 'Cashier' },
                  { key: null,       label: 'Ref / Note' },
                  ...(isAdmin ? [{ key: null, label: 'Actions' }] : []),
                ].map(({ key, label }) => (
                  <th key={label} onClick={() => key && toggleSort(key)} style={{
                    padding: '10px 14px', textAlign: 'left', fontSize: 10, fontWeight: 600,
                    letterSpacing: '0.10em', textTransform: 'uppercase', color: 'var(--ink-light)',
                    whiteSpace: 'nowrap', cursor: key ? 'pointer' : 'default', userSelect: 'none',
                  }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                      {label}
                      {key && sortBy === key && <ArrowUpDown size={10} style={{ opacity: .6 }} />}
                    </span>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={isAdmin ? 10 : 9} style={{ textAlign: 'center', padding: '3.5rem 0' }}>
                  <div style={{ width: 24, height: 24, border: '3px solid var(--border)', borderTopColor: 'var(--blue)', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto' }} />
                </td></tr>
              ) : rows.length === 0 ? (
                <tr><td colSpan={isAdmin ? 10 : 9} style={{ textAlign: 'center', padding: '3.5rem 0' }}>
                  <Receipt size={34} style={{ color: 'var(--border)', margin: '0 auto 10px', display: 'block' }} />
                  <p style={{ color: 'var(--ink-faint)', fontSize: 13, fontWeight: 300 }}>
                    {hasFilters ? 'No payments match your filters' : 'No payments recorded yet — they appear automatically when a sale is completed'}
                  </p>
                </td></tr>
              ) : rows.map(p => (
                <tr key={p.paymentCode} className="abk-row-hover" style={{ borderBottom: '1px solid var(--border-light)' }}>
                  <td style={{ padding: '11px 14px' }}>
                    <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--ink)' }}>{fmtDate(p.paymentDate)}</div>
                    {p.paymentTime && <div style={{ fontSize: 10.5, color: 'var(--ink-faint)', marginTop: 2, fontWeight: 300 }}>{fmtTime(p.paymentTime)}</div>}
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 11.5, fontFamily: 'monospace', color: 'var(--ink-mid)' }}>{p.paymentCode}</td>
                  <td style={{ padding: '11px 14px', fontSize: 13, fontWeight: 500, color: 'var(--ink)' }}>{p.customerName || '—'}</td>
                  <td style={{ padding: '11px 14px' }}>
                    <div style={{ fontSize: 12, color: 'var(--ink-light)', fontFamily: 'monospace' }}>{p.saleCode}</div>
                    {p.saleProductName && <div style={{ fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>{p.saleProductName}</div>}
                  </td>
                  <td style={{ padding: '11px 14px' }}><MethodBadge method={p.paymentMethod} /></td>
                  <td style={{ padding: '11px 14px', fontSize: 12, color: 'var(--ink-light)', fontWeight: 300 }}>{p.bankName || '—'}</td>
                  <td style={{ padding: '11px 14px' }}>
                    <span className="abk-serif" style={{ fontSize: 14, fontWeight: 600, color: 'var(--green)' }}>${fmt(p.amountPaid)}</span>
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 12, color: 'var(--ink-light)', fontWeight: 300 }}>{p.cashier || '—'}</td>
                  <td style={{ padding: '11px 14px', fontSize: 11.5, color: 'var(--ink-faint)', fontWeight: 300, maxWidth: 180 }}>
                    {p.transactionRef && <div style={{ fontFamily: 'monospace', color: 'var(--ink-mid)' }}>{p.transactionRef}</div>}
                    {p.notes && <div style={{ marginTop: 2 }}>{p.notes}</div>}
                    {!p.transactionRef && !p.notes && '—'}
                  </td>
                  {isAdmin && (
                    <td style={{ padding: '11px 14px' }}>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button onClick={() => openEdit(p)} title="Edit note / reference" style={{
                          width: 28, height: 28, borderRadius: 8, border: '1px solid var(--border)',
                          background: 'var(--cream-deep)', color: 'var(--ink-mid)',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
                        }}><Edit2 size={12} /></button>
                        <button onClick={() => setDeleteConfirm(p)} title="Delete payment" style={{
                          width: 28, height: 28, borderRadius: 8, border: '1px solid var(--red-border)',
                          background: 'var(--red-bg)', color: 'var(--red-text)',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
                        }}><Trash2 size={12} /></button>
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', borderTop: '1px solid var(--border-light)', background: 'var(--cream-deep)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>
            <span>Rows:</span>
            {[10, 20, 50, 100].map(n => (
              <button key={n} onClick={() => { setRowsPerPage(n); setPage(1); }} style={{
                padding: '2px 9px', borderRadius: 7, fontSize: 11, fontWeight: 500, cursor: 'pointer',
                background: rowsPerPage === n ? 'var(--blue)' : 'var(--card)',
                color: rowsPerPage === n ? '#fff' : 'var(--ink-faint)',
                border: `1px solid ${rowsPerPage === n ? 'var(--blue)' : 'var(--border)'}`,
              }}>{n}</button>
            ))}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>
            <span>{totalElements === 0 ? 0 : (page - 1) * rowsPerPage + 1}–{Math.min(page * rowsPerPage, totalElements)} / {totalElements}</span>
            {[
              { Icon: ChevronLeft,  action: () => setPage(p => Math.max(1, p - 1)),         disabled: page === 1 },
              { Icon: ChevronRight, action: () => setPage(p => Math.min(totalPages, p + 1)), disabled: page === totalPages },
            ].map(({ Icon, action, disabled }, i) => (
              <button key={i} onClick={action} disabled={disabled} style={{
                width: 26, height: 26, borderRadius: 7, border: '1px solid var(--border)',
                background: 'var(--card)', color: 'var(--ink-light)', cursor: disabled ? 'not-allowed' : 'pointer',
                opacity: disabled ? .35 : 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}><Icon size={13} /></button>
            ))}
          </div>
        </div>
      </div>

      {/* ── Edit modal (ADMIN) ───────────────────────────────────────── */}
      {editTarget && (
        <Modal onClose={() => setEditTarget(null)} maxWidth={420}>
          <ModalHeader title="Edit Payment" subtitle={editTarget.paymentCode} onClose={() => setEditTarget(null)} accent="var(--blue)" />
          <div style={{ padding: '1.2rem 1.4rem', display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{
              background: 'var(--cream-deep)', borderRadius: 10, padding: '10px 12px',
              fontSize: 12, color: 'var(--ink-light)', fontWeight: 300,
            }}>
              Amount, method, bank, cashier, and the linked sale are locked once recorded — only the transaction
              reference and note can be corrected here.
            </div>
            <div>
              <label className="abk-label">Transaction Ref</label>
              <input value={editForm.transactionRef} onChange={e => setEditForm(f => ({ ...f, transactionRef: e.target.value }))}
                className="abk-input" placeholder="e.g. TX-88213" />
            </div>
            <div>
              <label className="abk-label">Note</label>
              <input value={editForm.notes} onChange={e => setEditForm(f => ({ ...f, notes: e.target.value }))}
                className="abk-input" placeholder="Any note about this payment" />
            </div>
          </div>
          <ModalFooter>
            <BtnSecondary onClick={() => setEditTarget(null)}>Cancel</BtnSecondary>
            <BtnPrimary onClick={handleSaveEdit} disabled={saving}>
              {saving ? <><RefreshCw size={13} style={{ animation: 'spin 1s linear infinite' }} /> Saving…</> : <><CheckCircle size={13} /> Save</>}
            </BtnPrimary>
          </ModalFooter>
        </Modal>
      )}

      {/* ── Delete confirm (ADMIN) ───────────────────────────────────── */}
      {deleteConfirm && (
        <Modal onClose={() => setDeleteConfirm(null)} maxWidth={360}>
          <div style={{ padding: '2rem 1.6rem 1.4rem', textAlign: 'center' }}>
            <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'var(--red-bg)', border: '2px solid var(--red-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 14px' }}>
              <Trash2 size={22} style={{ color: 'var(--red-text)' }} />
            </div>
            <div className="abk-serif" style={{ fontSize: 17, fontWeight: 500, color: 'var(--ink)', marginBottom: 6 }}>Delete Payment</div>
            <p style={{ fontSize: 13, color: 'var(--ink-light)', marginBottom: 4, fontWeight: 300 }}>
              Payment <strong style={{ color: 'var(--ink)', fontWeight: 500 }}>{deleteConfirm.paymentCode}</strong> of
              <span className="abk-serif" style={{ fontWeight: 600, color: 'var(--green)', fontSize: 14 }}> ${fmt(deleteConfirm.amountPaid)}</span>
            </p>
            <p style={{ fontSize: 11, color: 'var(--red-text)', marginBottom: 20, fontWeight: 300 }}>
              This does not adjust the linked sale's paid amount — only removes this payment record.
            </p>
            <div style={{ display: 'flex', gap: 10 }}>
              <BtnSecondary onClick={() => setDeleteConfirm(null)}>Cancel</BtnSecondary>
              <BtnPrimary onClick={() => handleDelete(deleteConfirm.paymentCode)} color="#c53030">Delete</BtnPrimary>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
}

/* ════════════════════════════════════════════════════════════════════════════
   Banks tab — CRUD with search
   ════════════════════════════════════════════════════════════════════════════ */
function emptyBankForm() { return { name: '', accountNumber: '', branch: '', notes: '', active: true }; }

function BanksTab({ isAdmin, showSuccess }) {
  const [rows,          setRows]          = useState([]);
  const [totalElements, setTotalElements] = useState(0);
  const [totalPages,    setTotalPages]    = useState(1);
  const [loading,       setLoading]       = useState(true);
  const [search,        setSearch]        = useState('');
  const [page,          setPage]          = useState(1);
  const [rowsPerPage,   setRowsPerPage]   = useState(10);
  const [showModal,     setShowModal]     = useState(false);
  const [editingId,     setEditingId]     = useState(null);
  const [form,          setForm]          = useState(emptyBankForm());
  const [saving,        setSaving]        = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(null);

  async function load() {
    try {
      setLoading(true);
      const res = await getBanksPage({ page: page - 1, size: rowsPerPage, search });
      setRows(res.content ?? []);
      setTotalElements(res.totalElements ?? 0);
      setTotalPages(Math.max(1, res.totalPages ?? 1));
    } catch {
      setRows([]); setTotalElements(0); setTotalPages(1);
    } finally { setLoading(false); }
  }

  useEffect(() => {
    const t = setTimeout(load, search ? 350 : 0);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, rowsPerPage, search]);

  function openCreate() { setEditingId(null); setForm(emptyBankForm()); setShowModal(true); }
  function openEdit(b) {
    setEditingId(b.id);
    setForm({ name: b.name || '', accountNumber: b.accountNumber || '', branch: b.branch || '', notes: b.notes || '', active: b.active !== false });
    setShowModal(true);
  }

  async function handleSave() {
    if (!form.name.trim()) { alert('Bank name is required.'); return; }
    setSaving(true);
    try {
      if (editingId) await updateBank(editingId, form);
      else await createBank(form);
      setShowModal(false);
      showSuccess(editingId ? 'Bank updated' : 'Bank added');
      await load();
    } catch (e) { alert(e.message || 'Failed to save bank.'); }
    finally { setSaving(false); }
  }

  async function handleDelete(id) {
    try {
      await deleteBank(id);
      setDeleteConfirm(null);
      showSuccess('Bank deleted');
      await load();
    } catch (e) { alert(e.message || 'Failed to delete bank.'); }
  }

  async function handleToggleActive(b) {
    try {
      await updateBank(b.id, { ...b, active: !b.active });
      showSuccess(b.active ? 'Bank deactivated' : 'Bank activated');
      await load();
    } catch (e) { alert(e.message || 'Failed to update bank.'); }
  }

  return (
    <>
      {/* ── Search + Add ─────────────────────────────────────────────── */}
      <div className="abk-anim-fade-in abk-pay-filter" style={{ display: 'flex', gap: 8, marginBottom: '1rem' }}>
        <div style={{ flex: 1, position: 'relative' }}>
          <Search size={14} style={{ position: 'absolute', left: 11, top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-faint)', pointerEvents: 'none' }} />
          <input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}
            placeholder="Search bank name, branch, account…" className="abk-input" style={{ paddingLeft: 34 }} />
        </div>
        {isAdmin && (
          <button onClick={openCreate} style={{
            display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px',
            background: 'var(--blue)', color: '#fff', border: 'none', borderRadius: 11,
            fontSize: 13, fontWeight: 500, cursor: 'pointer', fontFamily: 'DM Sans,sans-serif',
            boxShadow: '0 2px 8px rgba(24,95,165,.3)', whiteSpace: 'nowrap',
          }}><Plus size={14} /> Add Bank</button>
        )}
      </div>

      {/* ── Table ─────────────────────────────────────────────────────── */}
      <div className="abk-anim-scale-in" style={{
        background: 'var(--card)', border: '1px solid var(--border)',
        borderRadius: 16, width: '100%', overflow: 'hidden',
        boxShadow: '0 2px 12px rgba(0,0,0,.06)',
      }}>
        <div style={{
          padding: '10px 16px', borderBottom: '1px solid var(--border-light)',
          background: 'var(--cream-deep)', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <div className="abk-serif" style={{ fontSize: 14, fontWeight: 500, color: 'var(--ink)' }}>Registered Banks</div>
          <span style={{ fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>{totalElements} banks</span>
        </div>

        <div className="abk-pay-table-wrap" style={{ overflowX: 'auto', width: '100%' }}>
          <table style={{ width: '100%', minWidth: 'max-content', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ background: 'var(--cream-deep)', borderBottom: '1px solid var(--border)' }}>
                {['Bank Name', 'Branch', 'Account Number', 'Status', 'Notes', ...(isAdmin ? ['Actions'] : [])].map(h => (
                  <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontSize: 10, fontWeight: 600, letterSpacing: '0.10em', textTransform: 'uppercase', color: 'var(--ink-light)', whiteSpace: 'nowrap' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr><td colSpan={isAdmin ? 6 : 5} style={{ textAlign: 'center', padding: '3.5rem 0' }}>
                  <div style={{ width: 24, height: 24, border: '3px solid var(--border)', borderTopColor: 'var(--blue)', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto' }} />
                </td></tr>
              ) : rows.length === 0 ? (
                <tr><td colSpan={isAdmin ? 6 : 5} style={{ textAlign: 'center', padding: '3.5rem 0' }}>
                  <Landmark size={34} style={{ color: 'var(--border)', margin: '0 auto 10px', display: 'block' }} />
                  <p style={{ color: 'var(--ink-faint)', fontSize: 13, fontWeight: 300 }}>
                    {search ? 'No banks match your search' : (isAdmin ? 'No banks yet — add one to accept bank payments' : 'No banks registered yet')}
                  </p>
                </td></tr>
              ) : rows.map(b => (
                <tr key={b.id} className="abk-row-hover" style={{ borderBottom: '1px solid var(--border-light)' }}>
                  <td style={{ padding: '11px 14px', fontSize: 13, fontWeight: 500, color: 'var(--ink)' }}>{b.name}</td>
                  <td style={{ padding: '11px 14px', fontSize: 12, color: 'var(--ink-light)', fontWeight: 300 }}>{b.branch || '—'}</td>
                  <td style={{ padding: '11px 14px', fontSize: 12, fontFamily: 'monospace', color: 'var(--ink-mid)' }}>{b.accountNumber || '—'}</td>
                  <td style={{ padding: '11px 14px' }}>
                    <span style={{
                      display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 11, fontWeight: 600,
                      padding: '2px 9px', borderRadius: 20,
                      background: b.active !== false ? 'var(--green-bg)' : 'var(--red-bg)',
                      color: b.active !== false ? 'var(--green)' : 'var(--red-text)',
                      border: `1px solid ${b.active !== false ? 'rgba(29,158,117,.25)' : 'var(--red-border)'}`,
                    }}>
                      {b.active !== false ? <CheckCircle2 size={10} /> : <Ban size={10} />} {b.active !== false ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td style={{ padding: '11px 14px', fontSize: 11.5, color: 'var(--ink-faint)', fontWeight: 300, maxWidth: 200 }}>{b.notes || '—'}</td>
                  {isAdmin && (
                    <td style={{ padding: '11px 14px' }}>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button onClick={() => handleToggleActive(b)} title={b.active !== false ? 'Deactivate' : 'Activate'} style={{
                          width: 28, height: 28, borderRadius: 8, border: '1px solid var(--border)',
                          background: 'var(--cream-deep)', color: 'var(--ink-mid)',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
                        }}>{b.active !== false ? <Ban size={12} /> : <CheckCircle2 size={12} />}</button>
                        <button onClick={() => openEdit(b)} title="Edit" style={{
                          width: 28, height: 28, borderRadius: 8, border: '1px solid var(--border)',
                          background: 'var(--cream-deep)', color: 'var(--ink-mid)',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
                        }}><Edit2 size={12} /></button>
                        <button onClick={() => setDeleteConfirm(b)} title="Delete" style={{
                          width: 28, height: 28, borderRadius: 8, border: '1px solid var(--red-border)',
                          background: 'var(--red-bg)', color: 'var(--red-text)',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
                        }}><Trash2 size={12} /></button>
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 14px', borderTop: '1px solid var(--border-light)', background: 'var(--cream-deep)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>
            <span>Rows:</span>
            {[10, 20, 50].map(n => (
              <button key={n} onClick={() => { setRowsPerPage(n); setPage(1); }} style={{
                padding: '2px 9px', borderRadius: 7, fontSize: 11, fontWeight: 500, cursor: 'pointer',
                background: rowsPerPage === n ? 'var(--blue)' : 'var(--card)',
                color: rowsPerPage === n ? '#fff' : 'var(--ink-faint)',
                border: `1px solid ${rowsPerPage === n ? 'var(--blue)' : 'var(--border)'}`,
              }}>{n}</button>
            ))}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--ink-faint)', fontWeight: 300 }}>
            <span>{totalElements === 0 ? 0 : (page - 1) * rowsPerPage + 1}–{Math.min(page * rowsPerPage, totalElements)} / {totalElements}</span>
            {[
              { Icon: ChevronLeft,  action: () => setPage(p => Math.max(1, p - 1)),         disabled: page === 1 },
              { Icon: ChevronRight, action: () => setPage(p => Math.min(totalPages, p + 1)), disabled: page === totalPages },
            ].map(({ Icon, action, disabled }, i) => (
              <button key={i} onClick={action} disabled={disabled} style={{
                width: 26, height: 26, borderRadius: 7, border: '1px solid var(--border)',
                background: 'var(--card)', color: 'var(--ink-light)', cursor: disabled ? 'not-allowed' : 'pointer',
                opacity: disabled ? .35 : 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}><Icon size={13} /></button>
            ))}
          </div>
        </div>
      </div>

      {/* ── Create/Edit modal ────────────────────────────────────────── */}
      {showModal && (
        <Modal onClose={() => setShowModal(false)} maxWidth={440}>
          <ModalHeader title={editingId ? 'Edit Bank' : 'Add Bank'} subtitle="Bank details" onClose={() => setShowModal(false)} accent="var(--blue)" />
          <div style={{ padding: '1.2rem 1.4rem', display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div>
              <label className="abk-label">Bank Name *</label>
              <input value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                placeholder="e.g. Commercial Bank of Ethiopia" className="abk-input" />
            </div>
            <div className="abk-pay-modal-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
              <div>
                <label className="abk-label">Branch</label>
                <input value={form.branch} onChange={e => setForm(f => ({ ...f, branch: e.target.value }))}
                  placeholder="e.g. Awash Branch" className="abk-input" />
              </div>
              <div>
                <label className="abk-label">Account Number</label>
                <input value={form.accountNumber} onChange={e => setForm(f => ({ ...f, accountNumber: e.target.value }))}
                  placeholder="Optional" className="abk-input" />
              </div>
            </div>
            <div>
              <label className="abk-label">Notes</label>
              <input value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))}
                placeholder="Optional" className="abk-input" />
            </div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12.5, color: 'var(--ink-mid)', cursor: 'pointer' }}>
              <input type="checkbox" checked={form.active} onChange={e => setForm(f => ({ ...f, active: e.target.checked }))} />
              Active (visible in the Sales-form bank picker)
            </label>
          </div>
          <ModalFooter>
            <BtnSecondary onClick={() => setShowModal(false)}>Cancel</BtnSecondary>
            <BtnPrimary onClick={handleSave} disabled={saving}>
              {saving ? <><RefreshCw size={13} style={{ animation: 'spin 1s linear infinite' }} /> Saving…</> : <><CheckCircle size={13} /> Save</>}
            </BtnPrimary>
          </ModalFooter>
        </Modal>
      )}

      {/* ── Delete confirm ───────────────────────────────────────────── */}
      {deleteConfirm && (
        <Modal onClose={() => setDeleteConfirm(null)} maxWidth={360}>
          <div style={{ padding: '2rem 1.6rem 1.4rem', textAlign: 'center' }}>
            <div style={{ width: 52, height: 52, borderRadius: '50%', background: 'var(--red-bg)', border: '2px solid var(--red-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 14px' }}>
              <Trash2 size={22} style={{ color: 'var(--red-text)' }} />
            </div>
            <div className="abk-serif" style={{ fontSize: 17, fontWeight: 500, color: 'var(--ink)', marginBottom: 6 }}>Delete Bank</div>
            <p style={{ fontSize: 13, color: 'var(--ink-light)', marginBottom: 4, fontWeight: 300 }}>
              Remove <strong style={{ color: 'var(--ink)', fontWeight: 500 }}>{deleteConfirm.name}</strong> from your bank list?
            </p>
            <p style={{ fontSize: 11, color: 'var(--ink-faint)', marginBottom: 20, fontWeight: 300 }}>
              Banks with existing payment history can't be deleted — deactivate them instead to keep past records intact.
            </p>
            <div style={{ display: 'flex', gap: 10 }}>
              <BtnSecondary onClick={() => setDeleteConfirm(null)}>Cancel</BtnSecondary>
              <BtnPrimary onClick={() => handleDelete(deleteConfirm.id)} color="#c53030">Delete</BtnPrimary>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
}
